name: Run Encrypted Script

on: [push]

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Script
        env:
          MY_SECRET: ${{ secrets.GETCODE }}
        run: |
          python -c "import os; print(os.environ['GETCODE'])"
