name: Use Secret in Workflow

on: [push]

jobs:
  use_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Secret Environment Variable
        env:
          GETCODE: ${{ secrets.GETCODE }}
        run: |
          echo "GETCODE is $GETCODE"

      - name: Run Script Using Secret
        env:
          GETCODE: ${{ secrets.GETCODE }}
        run: |
          python ma.py
